[[ -e ~/.bash/env ]] && source ~/.bash/env
[[ -e ~/.bash/config ]] && source ~/.bash/config
[[ -e ~/.bash/aliases ]] && source ~/.bash/aliases

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
